# Dynamics values of multi input and multi output
# builtin_interfaces/Time stamp
std_msgs/Header header
float64 sampling_time
float64 p_gain
float64 i_gain
float64 d_gain
float64 theta_desired
float64 theta_actual
float64 omega_actual
float64 segment_theta_relative
float64 segment_omega_relative
float64[] tension
float64 torque_input
float64[] external_force
float64 external_torque
int32   friction_mode
float64 friction_torque
float64 damping_coefficient
float64 input_alpha
float64 input_omega
float64 input_theta

