enable_color: true
enable_depth: true
align_depth.enable: true
enable_sync: true
depth_module.color_profile: "848,480,30"
depth_module.depth_profile: "848,480,30"
depth_module.enable_auto_exposure: false
depth_module.exposure: 20000
color_qos: SENSOR_DATA
depth_qos: SENSOR_DATA
color_info_qos: SENSOR_DATA
depth_info_qos: SENSOR_DATA
