#________________________________________________________
# Tool tip angle
#________________________________________________________

# Request
int8    mode #= 0    # ABSOLUTE=0, RELATIVE=1
float64 tiltangle    # degree
float64 panangle     # degree
float64 gripangle    # degree
---
# Response
bool success
