#________________________________________________________
# Tool tip position
#________________________________________________________

# Request
int8    mode #= 0    # ABSOLUTE=0, RELATIVE=1
geometry_msgs/Pose goal_position
---
# Response
bool success