#________________________________________________________
# Tool tip position
#________________________________________________________

# Request
string reference_type # absolute, relative
geometry_msgs/Pose goal_position
---
# Response
bool success